Feat/heatmap
neuefische/muc-22-2-team-pause pull request #44
Opened 2022-12-09 13:24 UTC by Ollekmc

Add heatMap pls review

2022-12-09 16:09 UTC, fannie-id commented on frontend/src/component/UserOverview.tsx
> +        <button onClick={openMap}>map </button>
`<button onClick={openMap}> map </button>`

2022-12-09 16:12 UTC, fannie-id approved these changes

2022-12-11 12:44 UTC, NickKlock requested changes

2022-12-11 12:44 UTC, NickKlock commented on frontend/src/component/HeatMap.tsx
> +                        geographies.map((geo) => {
arrow functions always return a value.

2022-12-11 12:44 UTC, NickKlock commented on frontend/src/component/HeatMap.tsx
> +    }[]>([])
you can create a type for that

2022-12-11 12:44 UTC, NickKlock commented on frontend/src/component/HeatMap.tsx
> +    }, [])
Someone else then your probably needs a day to understand your code here. maybe less for-each and more filter(), map() etc?

2022-12-11 12:45 UTC, NickKlock commented on frontend/src/component/HeatMap.tsx
> +        let output = threeLetterCodeList.map(setCount);
what is output suppose to mean? maybe u can be a bit more creative with your variable names.

2022-12-13 09:55 UTC, NickKlock approved these changes

2022-12-13 09:58 UTC, merged